package Ocean::Constants::EventType;

use strict;
use warnings;

use constant UNKNOWN                         => 'unknown';
use constant PING                            => 'ping';
use constant TOO_MANY_AUTH_ATTEMPT           => 'too_many_auth_attempt';
use constant SASL_AUTH_REQUEST               => 'sasl_auth_request';
use constant SASL_PASSWORD_REQUEST           => 'sasl_password_request';
use constant SASL_SUCCESS_NOTIFICATION       => 'sasl_success_notification';
use constant SASL_AUTH_COMPLETION            => 'sasl_auth_completion';
use constant DELIVER_SASL_PASSWORD           => 'deliver_sasl_password';
use constant SASL_AUTH_FAILURE               => 'sasl_auth_failure';
use constant HTTP_AUTH_REQUEST               => 'http_auth_request';
use constant HTTP_AUTH_COMPLETION            => 'http_auth_completion';
use constant HTTP_AUTH_FAILURE               => 'http_auth_failure';
use constant BIND_REQUEST                    => 'bind_request';
use constant SESSION_REQUEST                 => 'session_request';
use constant BOUND_JID                       => 'bound_jid';
use constant SEND_MESSAGE                    => 'send_message';
use constant DELIVER_MESSAGE                 => 'deliver_message';
use constant BROADCAST_INITIAL_PRESENCE      => 'broadcast_initial_presence';
use constant BROADCAST_PRESENCE              => 'broadcast_presence';
use constant DELIVER_PRESENCE                => 'deliver_presence';
use constant BROADCAST_UNAVAILABLE_PRESENCE  => 'broadcast_unavailable_presence';
use constant DELIVER_UNAVAILABLE_PRESENCE    => 'deliver_unavailable_presence';
use constant SILENT_DISCONNECTION            => 'silent_disconnection';
use constant ROSTER_REQUEST                  => 'roster_request';
use constant DELIVER_ROSTER                  => 'deliver_roster';
use constant DELIVER_ROSTER_PUSH             => 'deliver_roster_push';
use constant VCARD_REQUEST                   => 'vcard_request';
use constant DELIVER_VCARD                   => 'deliver_vcard';
use constant PUBLISH_EVENT                   => 'publish_pubsub_event';
use constant DELIVER_PUBSUB_EVENT            => 'deliver_pubsub_event';
use constant DISCO_INFO_REQUEST              => 'disco_info_request';
use constant DISCO_ITEMS_REQUEST             => 'disco_items_request';
use constant DELIVER_DISCO_INFO              => 'deliver_disco_info';
use constant DELIVER_DISCO_ITEMS             => 'deliver_disco_items';
use constant NODE_INIT                       => 'node_init';
use constant NODE_TIMER_REPORT               => 'node_timer_report';
use constant NODE_EXIT                       => 'node_exit';
use constant WORKER_INIT                     => 'worker_init';
use constant WORKER_EXIT                     => 'worker_exit';
use constant STREAM_INIT                     => 'stream_init';
use constant SEND_IQ_TOWARD_USER             => 'send_iq_toward_user';
use constant SEND_IQ_TOWARD_ROOM_MEMBER      => 'send_iq_toward_room_member';
use constant DELIVER_IQ_TOWARD_USER          => 'deliver_iq_toward_user';
use constant DELIVER_IQ_TOWARD_ROOM_MEMBER   => 'deliver_iq_toward_room_member';
use constant ROOM_INFO_REQUEST               => 'room_info_request';
use constant ROOM_LIST_REQUEST               => 'room_list_request';
use constant ROOM_MEMBERS_LIST_REQUEST       => 'room_members_list_request';
use constant DELIVER_ROOM_INFO               => 'deliver_room_info';
use constant DELIVER_ROOM_LIST               => 'deliver_room_list';
use constant DELIVER_ROOM_MEMBERS_LIST       => 'deliver_room_members_list';
use constant ROOM_SERVICE_INFO_REQUEST       => 'room_service_info_request';
use constant ROOM_INVITATION                 => 'room_invitation';
use constant ROOM_INVITATION_DECLINE         => 'room_invitation_decline';
use constant SEND_ROOM_MESSAGE               => 'send_room_message';
use constant DELIVER_ROOM_MESSAGE            => 'deliver_room_message';
use constant ROOM_PRESENCE                   => 'room_presence';
use constant LEAVE_ROOM_PRESENCE             => 'leave_room_presence';
use constant DELIVER_ROOM_INVITATION         => 'deliver_room_invitation';
use constant DELIVER_ROOM_INVITATION_DECLINE => 'deliver_room_invitation_decline';
use constant JINGLE_INFO_REQUEST             => 'jingle_info_request';
use constant DELIVER_JINGLE_INFO             => 'deliver_jingle_info';
use constant DELIVER_MESSAGE_ERROR           => 'deliver_message_error';
use constant DELIVER_PRESENCE_ERROR          => 'deliver_presence_error';
use constant DELIVER_IQ_ERROR                => 'deliver_iq_error';

1;
